#ifndef MICROMACHINES_INPUT_H
#define MICROMACHINES_INPUT_H

enum Input{
    PRESS_NONE,
    PRESS_UP,
    PRESS_DOWN,
    PRESS_LEFT,
    RELEASE_LEFT,
    PRESS_RIGHT,
    RELEASE_RIGHT
};

#endif //MICROMACHINES_INPUT_H
