//Object types
#define ID_STRAIGHT_TRACK 100
#define ID_CURVE_TRACK 101
#define ID_HEALTH_POWERUP 102
#define ID_BOOST_POWERUP 103
#define ID_ROCK 104
#define ID_CAR_1 105
#define ID_CAR_2 106
#define ID_CAR_3 107
#define ID_CAR_4 108
#define ID_OIL 109
#define ID_MUD 110
#define ID_HEALTH_BAR_BACK 111
#define ID_HEALTH_BAR_FRONT 112
#define ID_EXPLOSION 113
#define ID_MUD_SPLAT 114

//InputEnum
#define ACCELERATE 1
#define STOP_ACCELERATING 2
#define DESACCELERATE 3
#define STOP_DESACCELERATING 4
#define TURN_RIGHT 5
#define STOP_TURNING_RIGHT 6
#define TURN_LEFT 7
#define STOP_TURNING_LEFT 8

//Event types.
#define COMMAND 1
#define SNAPSHOT 2
#define ENTER_LOBBY 3
#define PLAY_AS_USER 4
#define PLAY_AS_BOT 5
#define ENTER_ROOM 6


//Scenes
#define SCENE_MENU 200
#define SCENE_LOBBY 201
#define SCENE_GAME 202

//Audio
#define SFX_CAR_ENGINE 300
#define SFX_CAR_BRAKE 301
#define SFX_CAR_EXPLOSION 302
#define SFX_BUTTON 303

//Pixel sizes (horizontal and vertical)
#define PIXELS_PER_BLOCK 50

#define HOR_PS_STRAIGHT_TRACK 250
#define HOR_PS_CURVE_TRACK 250
#define HOR_PS_HEALTH_POWERUP 50
#define HOR_PS_BOOST_POWERUP 50
#define HOR_PS_ROCK 50
#define HOR_PS_CAR 50
#define HOR_PS_OIL 100
#define HOR_PS_MUD 100

#define VER_PS_STRAIGHT_TRACK 250
#define VER_PS_CURVE_TRACK 250
#define VER_PS_HEALTH_POWERUP 50
#define VER_PS_BOOST_POWERUP 50
#define VER_PS_ROCK 50
#define VER_PS_CAR 100
#define VER_PS_OIL 50
#define VER_PS_MUD 50
