#ifndef MICROMACHINES_INPUTENUM_H
#define MICROMACHINES_INPUTENUM_H

enum InputEnum {
    ACCELERATE,
    STOP_ACCELERATING,
    DESACCELERATE,
    STOP_DESACCELERATING,
    TURN_RIGHT,
    STOP_TURNING_RIGHT,
    TURN_LEFT,
    STOP_TURNING_LEFT
};

#endif //MICROMACHINES_INPUTENUM_H
